### ISSUE TITLE
🆕 Software Suggestion | FairEmail

### ISSUE THREAD

**Issue by GrimPixel** [privacytools/privacytools.io#1248]
## Basic Information

**Name:** FairEmail
**Category:** Email Clients
**URL:** https://email.faircode.eu/

## Description

It is actively updated, comparing to K-9 and other clients, with privacy features.

**Comment by beerisgood** [comment]
What make it better then k9 - which doesn't need a buyed Pro version?
Also i read many times that the FairMail UI is worse then k9

**Comment by GrimPixel** [comment]
K-9 is very much discontinued.
I don't know where you read that UI thing, but there are also people who prefer FairEmail's UI.
https://www.slant.co/topics/11515/~free-email-clients-for-android

**Comment by blacklight447-ptio** [comment]
We maybe just edit the email page and split it into a section for phone based mail clients and desktop ones.

**Comment by GrimPixel** [comment]
This may lead to duplication. A filter may be better, I think.

**Comment by beerisgood** [comment]
> 
> 
> K-9 is very much discontinued.
>
What? Last commit is from Aug 31, 2019 
https://github.com/k9mail/k-9/commits/master

**Comment by GrimPixel** [comment]
OK, their last release is 2 Sep 2018. They just don't update it so often as before.
The commits of FairEmail is overwhelming:
https://github.com/M66B/FairEmail/commits/master

**Comment by beerisgood** [comment]
A program doesn't need a update if no problems exist.
And they active develop it, so i don't see any reason to remove it.
FairMail is much younger project, so of course it needs more update to got a stable branch like k9.

Also FairMail is crap. It needs the pro version to use all features. k9 have more and is completely free
But this is the way the dev make apps. Provide basic features with free and full only for Pro users. Of course that's okay but not for everyone.
Also the dev had tracking problems in the past with his apps

**Comment by GrimPixel** [comment]
> A program doesn't need a update if no problems exist.
https://github.com/k9mail/k-9/issues
No promblem? Is it 592 or 0 on your screen? Something went wrong on my browser or yours?
Nothing about security has been applied in recent 11 months?

> And they active develop it, so i don't see any reason to remove it.
Where did you find me saying that I want to remove K-9?

> FairMail is much younger project, so of course it needs more update to got a stable branch like k9.
Why do you think it's not stable? Any proof?
Also, it's FairEmail, not FairMail.

> 
> Also FairMail is crap. It needs the pro version to use all features. k9 have more and is completely free
You are screwing all PTIO members because they keep Stardard Notes on the site. Go open a new issue to appeal for removing Stardard Notes.

> But this is the way the dev make apps. Provide basic features with free and full only for Pro users. Of course that's okay but not for everyone.
I agree, but the decision is not made by only one person.

> Also the dev had tracking problems in the past with his apps
Are you referring this:
https://www.reddit.com/r/fossdroid/comments/9euh57/fairemail_vs_k9/
There is also a user who denied that they have telemetry in NetGuard.

**Comment by beerisgood** [comment]
> 
> Are you referring this:
> https://www.reddit.com/r/fossdroid/comments/9euh57/fairemail_vs_k9/
> There is also a user who denied that they have telemetry in NetGuard.

It's long time now so i don't know where this problem was posted but the telemetry problem was real in NetGuard. I think it was even over/ with Google.
After some users speak about it, the dev remove it and then denied that this was ever the case. Like in this reddit thread

**Comment by GrimPixel** [comment]
I just saw that people were talking about it. There are grounds for it:
https://forum.f-droid.org/t/netguard/819
https://forum.f-droid.org/t/netguard-fork-without-telemetry/3092

I have stopped using Netguard. Let's just keep an eye on FairEmail.

**Comment by SimonVanacco** [comment]
Honestly i do prefer FairEmail UI, and it is quite stable too. Based on what i know there is no reason to not include it in PrivacyTools suggestions.

**Comment by shortenjukebox** [comment]
I used K-9 Mail for eight years, and I honestly like FairEmail’s user experience significantly more.

* In the rare case I have to display remote images, images that are obviously tracking pixels remain blocked.
* To safeguard against phishing and tracking: After selecting a link, the URL is previewed in full before choosing to open it.
* Whenever possible, link previews also offer the ability to strip tracking parameters and change the URL to use HTTPS.
* Messages that fail [DKIM](https://tools.ietf.org/html/rfc6376), [SPF](https://tools.ietf.org/html/rfc7208), and/or [DMARC](https://tools.ietf.org/html/rfc7489) authentication are flagged.
* Specifying per-folder syncing is simpler and less confusing.
* Better dark mode design and user experience.
* The sending of messages can be delayed or scheduled.
* Snooze functionality extends what’s built into Android. The app can trigger notifications for old or opened messages.

I switched before the new K-9 Mail (pre-)releases, so perhaps others would recommend giving those a shot. However, to be frank, dealing with K-9’s austere design and experience, unimproved since I started using it, has turned me off from trying it myself. From the KitKat-era interface (especially awful in dark mode), to not being able to swipe a folder/inbox item to invoke an action, to something as simple as reordering accounts on the main screen being so unintuitive – all so frustrating for me. Even with the new pre-releases, K-9’s longstanding substandard experience really eroded my faith in any improvements being made.

Also, while measuring projects by number of commits can be shallow, FairEmail’s repository has 1,000 more commits than K-9 (at 10,000 commits) while being 10 years younger. The developer works on it every day and has been nice to talk to, and is receptive to code contributions.

Lastly, while S/MIME is locked away in the paid upgrade, it only [costs an euro](https://email.faircode.eu/donate/) now, for non-Google Play Services versions of the app.

I’m pretty confident to support its inclusion on PrivacyTools, it’s a worthwhile alternative to the tried-and-true K-9 Email.

**Comment by beerisgood** [comment]
I try FairEmail too before the k9 redesign and honestly never see back.

FairEmail is in all points better and I even pay the pro version.
I guess the problems I post in the past only affect old versions from the beginning but now everything works

**Comment by dngray** [comment]
Perhaps we could mention it as an alternative?
