### ISSUE TITLE
Go through Operating Systems section

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1376]
We have talked within the team that the OS page also needs going through like VPN was recently. We have some obscure recommendations which connection to privacy is not obvious at first (or even now that I am typing this).

See also: https://github.com/privacytoolsIO/privacytools.io/issues/1370

**Comment by Mikaela** [comment]
#1368 makes me wonder if we should copy https://github.com/privacytoolsIO/privacytools.io/issues/1346 to have more categories for OSes (depending on which we will list):

* For everyone (I think Fedora has been suggested for this one)
* With a bit CLI curiosity (I think Debian fits here due to distribution upgrades (Debian x -> Debian y) require config file editing)
* Advanced/enthustiastic (Arch, Void, Alpine, OpenBSD?)

I remember that we have discussed Devuan, Void and Alpine previously, but the context may have been favourite distributions and whether they make sense to list and I think we were leaning towards no (isn't it good that an issue was opened immediately so we don't have to remember random team chats? :sweat_smile:)

**Comment by dawidpotocki** [comment]
> I remember that we have discussed Devuan, Void and Alpine previously, but the context may have been favourite distributions and whether they make sense to list and I think we were leaning towards no (isn't it good that an issue was opened immediately so we don't have to remember random team chats? :sweat_smile:)

I was talking about Void (which I use) and Alpine as _possible_
replacements for Arch, but as I said, it doesn't make much sense to list
them and was suggesting Devuan, as it is direct alternative to Debian,
which we list as "main" recommendation.

**Comment by dngray** [comment]
Okay, so I've had think about this. These are requirements we should have:

1. Distribution recommendations must support [reproducible builds](https://reproducible-builds.org/).
2. Must not be OEM distributions designed to run on a hardware.
3. Must not be niche distributions, by this I mean things which basically nobody uses
4. Must be not some fork over politics or other related nonsense.

> and Alpine as _possible_ replacements for Arch

I do not believe this is a good idea. Arch Linux is a mainstream distribution with a lot of up to date documentation.

To be honest I don't think we should focus too much on advanced/enthusiast distributions. Arch Linux and Alpine Linux is enough for that. Alpine Linux is particularly nice for servers and does have some unique features such as [lbu](https://wiki.alpinelinux.org/wiki/Alpine_local_backup).

**Comment by dngray** [comment]
I'm thinking of doing away with the worth mentioning category, we've been trying to phase that out on the site because something either is or isn't worth mentioning. I am leaning towards a list that looks like this.

There are thousands of distributions out there and I really only want to recommend things are not niche, and are aimed at a wide community.

#### Desktop
These are aimed at Linux first-time users. They need to work out of the box with minimal configuration and maintenance. They are typically going to be options for people who've come from Windows.

- Ubuntu - stable lots of documentation, excellent choice for beginners.
- Fedora - another long time desktop distribution
- Manjaro - rolling release desktop

#### Advanced
Must provide some kind of advanced feature or purpose.

- Alpine Linux - ram disk, good for containers, hypervisor etc
- Arch Linux - good documentation well known and supported
- Debian - well known and supported by vendors
- Qubes OS - good hypervisor for people dealing with un-trusted files, want to use virtual machines without having to manage the hypervisor themselves.

#### Tor focused distributions
- Tails - amnesic
- Whonix - provides advanced Torification, physical isolation, etc.

I do not think we need to list distributions based on whether they support systemd or not. This is political bullshit and has no relevance to privacy.

That said, we've listed Alpine Linux, (not for that reason) but because it has some unique features such as being able to easily run from ram, and container usage.

**Comment by blacklight447-ptio** [comment]
Qubes is not a hypervisor though :p

**Comment by dngray** [comment]
> Qubes is not a hypervisor though :p

rather you know what i mean, a distribution where someone can use one lol.. but yes.

**Comment by DirkAmiably3829** [comment]
I'm against adding Void Linux.
Because it is not well documented.
wiki.voidlinux.org is currently unmaintained.
The alternative, docs.voidlinux.org, lacks content.

**Comment by Asbesbopispa** [comment]
Hey there, I'm usually lurking there because I find interesting discussions and I'd like to give my opinion on this matter. I'm not an expert tho, so feel free to ignore everything I'm writing on this post.

I was able to convince a person I care about to switch from Windows to a Linux OS (Linux Mint because it was the easiest choice for someone who's bad with computers). I feel like the warning about Windows 10, on the Operating Systems page, should be placed on top because a non-tech-savvy person could find it more interesting to learn first about the privacy problems of the most used PC OS.
I totally agree with this argument: 

> There are thousands of distributions out there and I really only want to recommend things are not niche, and are aimed at a wide community.

A tech-savvy person should be able to understand which distro is the best for them, but a non-tech-savvy one may not be able to do so; distros with good support and plenty of documentation can be truly helpful and I feel like it a guide about how to switch should be linked too. FireJail and ufw/gufw should be suggested too, they're nice tools for someone who's not running something designed for privacy and security. Encrypting the system would be a nice addition too, because while it's mostly a security matter, it's really easy to enable on most distros.

Thank you all for your work, I appreciate what you're doing.

**Comment by DirkAmiably3829** [comment]
Linux Mint is not good.
It does not update the kernel by default. Leave the vulnerability.
The CJK input method installer is also unfriendly.

**Comment by dngray** [comment]
While we're at it we should remove Replicant as well from the mobile section, as this really isn't usable anymore.

**Comment by Asbesbopispa** [comment]
> Linux Mint is not good.
> It does not update the kernel by default. Leave the vulnerability.
> The CJK input method installer is also unfriendly.

I missed your comment somehow, I apologize.
By the way, I'm not suggesting Linux Mint, I was only talking about my past experience (it happened many years ago).

> While we're at it we should remove Replicant as well from the mobile section, as this really isn't usable anymore.
> 
> In regard to PC Live Operating Systems, this will become "Advanced" and we will use a badge to indicate if a distribution supports live-cd style booting, as a lot do.

Thank you for your work; encrypting the system should be suggested too, since it's painless to enable in Basic distros
