### ISSUE TITLE
📝 Correction | Add Pricing to NextDNS

### ISSUE THREAD

**Issue by xDazlD** [privacytools/privacytools.io#1927]
## Description
NextDNS is now charging to have more than 300,000 queries a month. They charge $1.99 a month for unlimited queries.

## Why I am making the suggestion
I think it should be mentioned on the site that the service isn't free. The email provider section also lists prices.

## My connection with the software

Just a user.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by danarel** [comment]
But NextDNS does allow you to be a free user, so there is a free option. If you notice on the email section, ProtonMail for example says FREE, even though they charge for additional features.

I'd argue that NextDNS would be listed as free still since that is an option. So I would not recommend adding pricing.

**Comment by xDazlD** [comment]
I think it's important to look at how much 300,000 queries is a month. My phone can hit that by itself and my home network is currently at 3.2 million requests in the last month.
Not sure if my network usage represents a standard user or not. Would probably need to ask a few other people for stats on their networks.

**Comment by filips123** [comment]
What about adding additional "freemium" category and add NextDNS, ProtonMail and other such services there?

**Comment by scafroglia93** [comment]
For $ 1.99 a month for all it offers?
Then we complain that the projects are closed

Thanks to NextDNS, the open source of the IoC lists previously used only for the pihole niche is being rediscovered

I speak as a contributor to the service through their github

**Comment by danarel** [comment]
Other team members may want to chime in, but I don't think we need to start listing services with free options with "freemium" or a price.

This would apply to many, even such services as Bitwarden, which offers free and paid tools. 

I think listing it as free is fine because the site states clearly that NextDNS only protects 300,000 and the user can decide if that's enough for them or not.

**Comment by xDazlD** [comment]
Maybe add a note saying the first 300,000 are free and then you have to pay, instead of just listing a price.

**Comment by danarel** [comment]
I think that's still overkill. Again, going back to other examples, I don't think we need to be saying "you can only send 500 emails a day" on ProtonMail free etc.

At some point, users also have to research the choices they want to make.

**Comment by Mikaela** [comment]
I agree with jacob from #dev:privacytools.io on closing this.

* I don't like the idea of adding another column or anything that is provider specific for single DNS provider.
* There are 300k free queries and after that NextDNS works as a normal resolver (instead of like forwarding all your queries to their "now you have to pay page") https://nextdns.io/pricing
* If you connect to their resolvers without specifying configuration, you may never even be aware of the limitation of 300k queries/month.
* If the user just wants to know if the Firefox provided resolvers are listed here and just use the Mozilla default, they won't be affected either.
