### ISSUE TITLE
🆕 Software Suggestion | HardenedBSD

### ISSUE THREAD

**Issue by FreddyMarsden** [privacytools/privacytools.io#1975]
## Basic Information

**Name:** HardenedBSD
**Category:** Advanced Operating Systems
**URL:**  [hardenedbsd.org](https://hardenedbsd.org/)
**GitHub** [github.com/HardenedBSD/hardenedBSD](https://github.com/HardenedBSD/hardenedBSD)
**.onion link** [lkiw4tmbudbr43hbyhm636sarn73vuow77czzohdbqdpjuq3vdzvenyd.onion](http://lkiw4tmbudbr43hbyhm636sarn73vuow77czzohdbqdpjuq3vdzvenyd.onion/)

## Description

A security-enhanced fork of FreeBSD. The HardenedBSD Project is implementing many exploit mitigation and security technologies on top of FreeBSD. The project started with Address Space Layout Randomization (ASLR) as an initial focal point and is now implementing further exploit mitigation techniques.

## Why I am making the suggestion

> HardenedBSD has many mitigations OpenBSD does not such as CFI, SafeStack, SEGVGUARD, a proper W^X implementation and more but it lacks things OpenBSD has such as LibreSSL, a hardened malloc etc...

(Taken from [here](https://madaidans-insecurities.github.io/openbsd.html))

## My connection with the software

None.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
Looks to be an interesting project, however I am not sure how I feel about adding it.

There were other things that were not added (Gentoo etc), because if a reader thinks they require that for their use case then they probably don't need us to tell them.

I imagine projects like HardenedBSD would be best suited to specialist applications (mostly in the server segment) where those extra mitigations are useful.
