### ISSUE TITLE
🆕 Software Suggestion | BraxRouter

### ISSUE THREAD

**Issue by vdeepp** [privacytools/privacytools.io#1981]
## Basic Information

**Name:**
BraxRouter

**Category:**
Hardware

**URL:**
https://www.youtube.com/watch?v=gL2qbWdLZig
https://brax.me/prod/host.php?f=_store&h=rob&p=&version=

## Description
Rob Braxman is a very experienced privacy guru and maker of this fantastic piece of hardware/software.
**I HIGHLY RECOMMEND THAT U WATCH THE YOUTUBE VIDEO. IT TAKES 20MINS TO WATCH BUT HE WILL EXPLAIN EVERY DETAIL TO U!!!**

## Why I am making the suggestion
Because i think this piece of hardware will fit in the upcoming hardware section.

 Raspberry PI 4 2GB with Brax VPN/TOR Router Software and custom case (Complete) - Wired or Wifi mode.

Why do you need a VPN Wifi router if you can install the VPN software on each device?

First of all, this supports unlimited devices.

Second your guests will not have VPN access normally and they will reveal your IP address and location. And you will be tracked by Facebook without a FB account.

And third, there are many devices that do not allow you to install a VPN on it like Kodi, Apple TV or your smart TV or home automation IOT devices.

A BraxWifi Router can shift to three uses. VPN Mode routes the Wifi traffic to BytzVPN (shipped preconfigured). It can also go to TOR mode so it functions as a TOR Router. And then you can operate it also as a normal Wifi router (Open mode).

A BraxWifi Router is designed to be left attached to your existing Wifi Router for alternate Wifi access. It gives a secondary Wifi.

This router will obfuscate its Mac Address and will foil apps like Facebook from tracking your location using Wifi Triangulation.

This is a complete solution and includes hardware and software. Please supply your own Ethernet cables.

This version supports Wired Router mode (no-Wifi) so all Ethernet traffic can be routed. Requires that you use a USB 3.0 Gigabit Ethernet adapter.

User Manual
https://brax.me/f/braxwifi-v3.e404.pdf/T4AZ5e0fce723cd816.61882430

## My connection with the software

My only connection is that i am subscribed to his yt channel

- [ ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment]
The video suggests that a VPN gives you privacy. This is generally not true. If you want to be anonymous on the internet you should use tor.

https://www.privacytools.io/providers/vpn/#info

**Comment by vdeepp** [comment]
Yes i also have read that on the privacytools site.
But remember the router also has a function to be a networkwide tor router.

**Comment by ph00lt0** [comment]
But really this you can do with so many routers. I really do not see the added value. A lot of routers have this option build in and it's easy to install OpenWRT on a lot of routers and go from there.

**Comment by Asbesbopispa** [comment]
I get what you're saying and maybe a complete solution could be helpful for non-tech-savvy people but there are some problems:

1. I can't find the source code of the BraxRouter software, but I read on the website it costs 99$ so I don't think the code is open source.

2. There are alternatives like OpenWRT, DD-WRT and more which are able to solve the same problem that BraxRouter is trying to solve; they're free and you can add the Pi-Hole software.

3. PTIO provided some guidelines which are mandatory for a VPN to be included in the list. The VPN seems like to have the registered address in the USA giving the following reason:

" VPN's Outside the US is not a Good Thing!
US laws protect us from direct attacks on our servers by 3-Letter agencies without cause. There is no rule that stops a 3-letter agency from hacking or extracting information from servers that are not based in the US! So when someone boasts (like NordVPN) that their servers are outside the USA, be wary!"

This is misleading and I invite you to read this: https://www.privacytools.io/providers/#ukusa
While I think there's not really a safe country for a VPN in this world, USA security services issued gag orders in the past, spied on people all over the world thanks to backdoors and many other methods. I can't find an independent audit too. If someone wants to pay by not going through PayPal, they need to send a mail to this guy. I can't really express an opinion about BytzTor because I couldn't figure it out how it works, but I can't really see the usefulness of it when one's running an home OS because they would still leak info and you still have a unique fingerprint with your browser.

I don't feel comfortable with this service, but I hope to be proved wrong.

**Comment by ph00lt0** [comment]
Please just close this issue. This product is very irrelevant. There are no certifications, no open source code, routing through USA. Also this is not an plug and play solution as advertised.

**Comment by dngray** [comment]
>  US laws protect us from direct attacks on our servers by 3-Letter agencies without cause. There is no rule that stops a 3-letter agency from hacking or extracting information from servers that are not based in the US! So when someone boasts (like NordVPN) that their servers are outside the USA, be wary!"

Also in regard to that, those laws don't actually protect people from the US either.

It's a known fact that the FVEY related countries spy on each other's citizens. The US would most certainly be gaining data from their counterparts at the GCHQ for example.
