### ISSUE TITLE
🆕 Software Suggestion | Behave!

### ISSUE THREAD

**Issue by Mikaela** [privacytools/privacytools.io#1998]
## Basic Information

**Name:** Behave!
**Category:** Browser extensions
**URL:** https://github.com/mindedsecurity/behave

## Description

Behave is a browser extension that detects port scanning performed by websites. E.g. [Ebay](https://www.techradar.com/news/ebay-is-port-scanning-users-pcs) has been caught up doing this.

## Why I am making the suggestion

I think it's interesting to know when that happens and it's a potential privacy issue which is why sofware such as Tor Browser has prevented it. I think PrivacyTools may wish to keep an eye on it.

## My connection with the software

I have no connection, I learnt of it from this [Ghacks article earlier this month](https://www.ghacks.net/2020/07/05/behave-for-chrome-and-firefox-warns-you-of-port-scans-and-local-attacks/).

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by hugoncosta** [comment]
Although I certainly applaud increasing awareness of any tactics companies might be using to decrease our privacy, the software does just that, warn. To me, it'd be a great addition when it/another came up with a way to block these requests instead of just warning us it's happening.

Looking at this from an unexperienced user, I know ebay does it's best to track my behaviour, but I still need to use their services, thus I want all the software I can get that will block those tactics.

**Comment by lynn-stephenson** [comment]
This issue should be closed. @freddy-m
