### ISSUE TITLE
❌ Software Removal | uMatrix Development has ended

### ISSUE THREAD

**Issue by danarel** [privacytools/privacytools.io#2057]
As per gHacks, uMatrix is dead.

https://www.ghacks.net/2020/09/20/umatrix-development-has-ended/

Not that it needs to come down immediately, but worth watching since it will be outdated at some point and a replacement or fork will need to introduced.

**Comment by dngray** [comment]
It does appear to be so. What I'm currently checking out is how much functionality is covered by uBlock in advanced mode. A number of people seem to be using that (including Raymond Hill).

These days its mostly 3rd-party JavaScript people care about, particularly in regard to advertising networks.

NoScript obviously provides some of the finer grade control (allowing/blocking of each scripts) but I imagine most people would be allowing all 1st party stuff anyway. 

If there is advertising code in there, it is trivial to tie it up with the page layout (ie make the page not load if the advertising code isn't there). Sites don't seem to do this fortunately and therefore rely on 3rd party JavaScript provided by the advertising networks.

I think most people likely whitelist the other things (css, images, media, xhr, frame etc) and just use with [blocking 1st party scripts](https://github.com/gorhill/uMatrix/wiki/How-to-block-1st-party-scripts-everywhere-by-default) mode, otherwise you'd have to enable about 10 things to make a site load. uBlock does support blocking media of a [certain size](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-large-media-elements) too.

The other thing I have wondered about, is if you used uMatrix in an really strict mode (blocking images, css etc) that would make your fingerprint quite unique.

I wonder what @Thorin-Oakenpants thinks.

**Comment by dngray** [comment]
Although by not using uMatrix, or NoScript, if for example you enabled JavaScript such as in this example, it appears you would get googletagmanager.com

![1600659879](https://user-images.githubusercontent.com/48640805/93731580-27012a80-fbbd-11ea-9fc4-4b8af0919f8a.png)

You'd either then need a list loaded that blocks that specifically,

**Comment by dngray** [comment]
You get most of the same functionality with [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) or [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode). The other thing that is nice is that uBlock is a [recommended extension](https://support.mozilla.org/kb/recommended-extensions-program), and was a priority with Fenix https://github.com/mozilla-mobile/fenix/issues/5630
