### ISSUE TITLE
🆕 Software Suggestion | blindsend

### ISSUE THREAD

**Issue by filiprd** [privacytools/privacytools.io#2082]
## Basic Information

**Name:** blindsend
**Category:** File Encryption
**URL:** https://github.com/blindnet-io/blindsend

## Description

Blindsend is an open-source tool for end-to-end encrypted file transfer between two agents. It provides a server with a REST API for managing file exchange workflows, and a web client which handles encryption and decryption of files on agents' local machines. There is also a java client library for blindsend.

Blindsend uses algorithms like Argon2id, BLAKE2b, XSalsa20, and XChaCha20-Poly1305. The project is under active development. 

## Why I am making the suggestion

We have started working on blindsend with the main aim to make the implementation of end-to-end encrypted file transfers easier for software developers who do not have expertise in the cryptography domain. Although blindsend is available as SaaS, we are developing client libraries so that software engineers can use blindsend in their projects as well. We made blindsend open source so that anyone can use it.

## My connection with the software

I am participating in the developer of blindsend.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by lynn-stephenson** [comment]
Blindsend appears to be in beta/alpha still, making it only applicable for worth mentioning section. Since there is a web UI, there is no *concrete* guarantee that the client can't *easily* be modified to extract the encryption keys, and hence the files. This isn't just an issue with your application though, it's pretty widespread.

Doesn't make it anymore OK. It just doesn't compete with [OnionShare](https://onionshare.org/), which is over the Tor network, and provides the guarantees that the I mentioned.

**Comment by lynn-stephenson** [comment]
@freddy-m This is ready to be closed.
