### ISSUE TITLE
🆕 Software Suggestion | Windscribe VPN

### ISSUE THREAD

**Issue by specter78** [privacytools/privacytools.io#2094]
## Basic Information

**Name:** windscribe
**Category:** VPN
**URL:** https://windscribe.com

## Description
No logging VPN service with generous free tier. 

## Why I am making the suggestion
Their features and privacy policy looks good enough. Moreover, it is almost comparable to ProtonVPN on thatoneprivacysite. 

I mainly want to know whether this VPN can be trusted. 

## My connection with the software

None. 

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
> Moreover, it is almost comparable to ProtonVPN on thatoneprivacysite.

While ThatOnePrivacySite is a useful site, don't just look at the columns and do a numerical comparison. There are other factors  at play also.

More importantly this provider does not fit with our criteria as there is no source code or [third party audits](https://www.reddit.com/r/Windscribe/comments/csap7c/third_party_security_audit/).

Windscribe ownership appears to be Canadian based. On a side note [RestorePrivacy did a review (September 2019)](https://restoreprivacy.com/vpn/reviews/windscribe/) on this. Notably they mention "Uses IKEv2 as default protocol (rather than OpenVPN)", I wonder if that's still true.
