### ISSUE TITLE
✨ Feature Suggestion | Privacy tweaks for chromium based browsers

### ISSUE THREAD

**Issue by specter78** [privacytools/privacytools.io#2095]
## Description

While Firefox is recommended, performance and web experience is not good enough. 

Chromium based browsers like ungoogled chromium and brave boasts of privacy. I'm suggesting tweaks (chrome://flags) that can be done to make it more secure.

**Comment by dngray** [comment]
The issue with Chromium is that there simply aren't the same kind of features available as there is with Firefox in regard to privacy such as anti-fingerprinting etc.

The issue with Ungoogled Chromium is they don't have a good distribution mechanism see https://github.com/privacytools/privacytools.io/issues/1973#issuecomment-660018282 binaries are built by third parties, and therefore decided that it would not be added.

Firefox performance has improved over the years and is very comparable to Chromium these days. In some ways it is actually faster.

- [Firefox 77 / 78 Beta vs. Chrome 83 Linux Browser Benchmarks](https://www.phoronix.com/scan.php?page=article&item=chrome83-firefox77-linux&num=1)
- [Firefox 72 vs. Chrome 80 Browser Performance On Ubuntu Linux With AMD Ryzen](https://www.phoronix.com/scan.php?page=article&item=chrome-80-benchmarks&num=1)

If you're having trouble with performance on Firefox, I would look very carefully at the extensions you're running, and check `about:performance`.

**Comment by specter78** [comment]
> binaries are built by third parties

This is no longer true, at least for Mac, as the binaries are built using GitHub Actions (see https://github.com/ungoogled-software/ungoogled-chromium-macos).

Regarding performance, I have just ublock origin as extension and browsing performance on chromium is much better than Firefox (at least for me).

**Comment by dngray** [comment]
> This is no longer true, at least for Mac, as the binaries are built using GitHub Actions (see https://github.com/ungoogled-software/ungoogled-chromium-macos).

There appears to be no binaries for windows: https://github.com/orgs/ungoogled-software/packages?repo_name=ungoogled-chromium-windows

There would need to be binaries universally for all platforms.

> Regarding performance, I have just ublock origin as extension and browsing performance on chromium is much better than Firefox (at least for me).

In any case it won't be much of an option soon as Manifestv3 is in stable. It's not even certain whether or not uBlock will continue to be supported on Chromium based browsers.

**Comment by lynn-stephenson** [comment]
Until Ungoogled Chromium has official releases for all popular desktop platforms(MacOS, Windows, and Linux), and also has _safe_ automatic updates, I do not believe it will be worthy of recommendation.

Installing extensions is also not easy, and would be a requirement if there are no internal security features (which there isn't).

**Comment by lynn-stephenson** [comment]
Until Ungoogled Chromium has official releases for all popular desktop platforms(MacOS, Windows, and Linux), and also has _safe_ automatic updates, I do not believe it will be worthy of recommendation.

Installing extensions is also not easy, and would be a requirement if there are no internal security features (which there isn't).

**Comment by zespire** [comment]
For windows, there's a convenient way to install Ungoogled Chromium and have automatic updates [https://github.com/iklevente/ChromiumForWindows](https://github.com/iklevente/ChromiumForWindows). You just need to install Chromium-ungoogled_Installer_x64.exe once which will automatically check and update ungoogled Chromium to the latest version like a normal browser would.

The extensions 'hassle' can be easily solved with [https://github.com/NeverDecaf/chromium-web-store](https://github.com/NeverDecaf/chromium-web-store) which lets you install extensions from Chrome Web Store without a google account similar to edge. On the plus side, it does not show annoying developer extension warnings popups.

The main issue with Ungoogled Chromium would be the lack of anti-fingerprinting measures and 'slower updates' (it's about a few days slower than chrome updates though with extra slowdown since binaries are built by third parties), however is the best choice for a Chromium based browser.

The 2nd best chromium browser is Iridium browser, however it contains some bugs (as you can't disable extensions and can only remove extensions from its top right menu) and has way slower updates than ungoggled chromium (still stuck on v8.5.210.20)

The last options (that are poor choices for privacy) would be chromium itself (fastest updates) with [https://github.com/iklevente/ChromiumForWindows](https://github.com/iklevente/ChromiumForWindows) for automatic updates, Microsoft edge, Vivaldi browser and maybe brave browser.

It'd be great if Ungoogled Chromium received more attention and support so we would finally have a proper full-fledged private chromium based browser.
