### ISSUE TITLE
How to host✨ Feature Suggestion | 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacytools/privacytools.io#2106]
## Description

Hosting is a way of keeping your data in your own control/hands. 
The term hosting is used all over the website, but how do we do it and what are the best practices for selfhosting while taking privacy and security in concern?
Is it better to use a VPS or a dedicated server? 
These could be question that people have when visiting the site and being fresh in the privacy environment. 
I think it would be a good idea to guide these people that want to enhance their privacy, because there is nothing on the site that explains it, yet the term is all over the place.

I hope i explained it well for u to understand. English is not my native language

**Comment by wylel** [comment]
I think this is a good idea, however there are countless guides online for it. Curate those and link to the best ones? Maybe a better place to add on the Wiki when that gets going?

**Comment by GintokiHub** [comment]
I feel a need for secure by design server OS or however a server is setup.  
With a backup by design push ( sort of a joke of 'nudging' term). 
Along with a UI which is on point. 
Whether this would be payed or not for the OS or whatever, just verified builds people would be able to pop in a virtual environment. Or via a sort of script or combo thereof hosted on any / multiple git hostage site(s). 
+ something like quickbox.io (just giving a project name as an example not claiming it has the above design implementations.

**Comment by GintokiHub** [comment]
If any people here or over at privacytools other channels for coms have some project coming up with the above I would love to know.
It is not that I don't know about projects, or am saying they are all bad or anything like that.
Just for making it mainstream ENOUGH. As I believe self-hosting as a "mainstream" hobby / privacy whatever is just a pipe dream at the moment.

**Comment by lynn-stephenson** [comment]
It should not matter _what_ instance of software you use. Which is why we are advocating for more secure software that reduce the trust you place on providers.

We already have a lot on our plate with auditing and looking into software recommendations. We should not have to keep up with "how to securely use and operate a VPS, and nextcloud instance" for example. Or link to guides that may be outdated, or use insecure methods.

Our target demographic is average users. Not developers, or IT folk who can run Virtual Private Servers, and get NextCloud instances running. Perhaps we will run a section for developers and IT folk alike, but that is not the case for now.
