### ISSUE TITLE
🆕 Software Suggestion | Add a Chromium based browser

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [privacytools/privacytools.io#2111]
**Category:**
Browser Recommendations For Desktop 
Browser Recommendations For iOS

## Why I am making the suggestion
In some use cases (often while working for a company) you just cant go around the fact that u have to use a Chromium based browser. 
For whatever the reason may be. 

I personally dont know if there are any good Chromium based browsers, but i can imagine people having the need of using them and visit Privacytools.io for some guidance. 

I don't think that they should be recommended based on that in the past, i didn't see any recommendation for it (i think at least), but i hope they maybe fit into the critera of "worth mentioning".

**Edit:**
Fixed some typos.
Also im sorry this should have the _enhancement_ label instead of _software suggestion_.

**Comment by LongJohn-Silver** [comment]
If I'm not wrong, there can't be a truly Chromium based browser on iOS because Apple forces developers to use their WebKit engine, so I guess it's kind of pointless to recommend other browsers that aren't as private as Firefox if they are going to behave pretty much the same way.

As for desktop browsers, at some point Brave was listed, but the developers asked it to be removed because followers of PT used to go to their repository and ask them to change or add X or Y and they didn't want to handle those people. Also, it's CEO it's a bit of a homophobic, and their whole cryptocurrency thing is a bit shady. As for the rest of the Chromium based stuff out there, it's really hard to maintain a private fork because of how it's released, you need to remove all of Google's blobs while also maintaining a browser up to date (which is a really hard work). The only more or less good options are Brave, Iridium, ungoogled Chromium and maybe Vivaldi (its CSS is closed source, though), but I'm not sure if they are updated so often.

**Comment by samuel-lucas6** [comment]
It would make sense to recommend a Chromium browser since they're so popular, but there are basically no good browsers from a privacy perspective. Most people would probably agree that the best is Ungoogled Chromium, but it requires manual updates. This is a problem, especially for the average user, since browsers are the type of software that need to remain up-to-date. Brave is seen as dodgy by many people due to the affiliate link scandal, the cryptocurrency stuff, etc. However, it's still a lot better than many other browsers. I've read that Vivaldi uses some analytics service that gets pinged every 24 hours (see the [privacy policy](https://vivaldi.com/privacy/browser/)), and it can't be built from source. The other Chromium browsers are either closed source or not updated regularly enough to be recommended.

**Comment by wylel** [comment]
Although I agree with @samuel-lucas6 I think listing Ungoogled-Chromium as an option, with the disclaimer, is not a bad idea. In the same terms, a user not being able to find a Chrome replacement, after hearing how much faster and awesome Chrome is, might just keep using Chrome instead of trying out another option if there is not one listed. Open to objections on this, of course.

**Comment by lynn-stephenson** [comment]
@wylel I don't think that'll work. PrivacyTools' target demographic is average users.

They won't be able to build Ungoogled Chromium, and recommending them to download binaries from a wide varity of sources is just asking for trouble. (It's even a warning in the official repository)

Again, we're targeting average users. The user experience is just too poor to recommend.
