### ISSUE TITLE
❌ Software Removal | TUTANOTA - German government force backdoor

### ISSUE THREAD

**Issue by udf2457** [privacytools/privacytools.io#2148]
https://www.heise.de/news/Gericht-zwingt-Mailprovider-Tutanota-zu-Ueberwachungsfunktion-4972460.html

**Comment by LongJohn-Silver** [comment]
Please read articles fully, even more so if they are not in English since it will be harder for admins to verify what it says.

Literally from the article: 

**German:**

[Update, 30.11., 12 Uhr] Wie Tutanota betonte, betrifft die Überwachungsmaßnahme nur die neu eingehenden unverschlüsselten E-Mails. Bereits verschlüsselte Daten sowie Ende-zu-Ende verschlüsselte E-Mails in Tutanota kann das Unternehmen nicht entschlüsseln. 

[Update] Außer Tutanota speichern auch einige andere Anbieter alle eingehenden Mails in verschlüsselter Form. Bei Protonmail ist das ebenfalls Standard, Posteo und Mailbox.org bieten die Verschlüsselung als Option an. Einen Überblick über die Zahl der Anfragen von Behörden gibt Tutanota in seinem Transparenzbericht.

**English:**

[Update, 30.11., 12 o'clock] As Tutanota emphasised, the monitoring measure only affects newly incoming unencrypted e-mails. Already encrypted data as well as end-to-end encrypted e-mails in Tutanota cannot be decrypted by the company.

[Update] Apart from Tutanota, some other providers also store all incoming mails in encrypted form. For Protonmail this is also standard, Posteo and Mailbox.org offer encryption as an option. Tutanota gives an overview of the number of requests from authorities in its transparency report.

----

In my opinion this doesn't deserve a delist, maybe a warning but it is stupid to not use encryption in something like e-mails, and anyway e-mails are not supposed to be used to communicate sensitive information.

**Comment by ph00lt0** [comment]
Every company has to comply with court orders. As long as they are transparent and do not undermine security and privacy I do not see a problem with this. Email is not really secure anyway, no rolling keys even in PGP. When using unencrypted email to Tutanota (or Protonmail etc) you cannot expect this level of privacy. If Tutanota would compromise your privacy by stealing your keys f.x. it would be more problematic. 
Eitherway this anti-encryption policy-making is a worrying trend. However it is still valid to recommend Tutanota to the masses to protect themselves from companies like Google indexing private communications.

**Comment by grande-mephistopheles** [comment]
> Every company has to comply with court orders. As long as they are transparent and do not undermine security and privacy I do not see a problem with this. Email is not really secure anyway, no rolling keys even in PGP. When using unencrypted email to Tutanota (or Protonmail etc) you cannot expect this level of privacy. If Tutanota would compromise your privacy by stealing your keys f.x. it would be more problematic.
> Eitherway this anti-encryption policy-making is a worrying trend. However it is still valid to recommend Tutanota to the masses to protect themselves from companies like Google indexing private communications.

I agree, as Tutanota was completey transparent with the court order and it's *not* a backdoor, per se. They are monitoring **unencrypted** emails from/to this specific user to obey the valid court rule. The user/anyone else is free to use the intermediary encryption to avoid this and Tutanota even encourages to do so.

**Comment by freddy-m** [comment]
See @LongJohn-Silver 's comment.
