### ISSUE TITLE
📝 Correction | https://www.privacytools.io/providers/dns/ - Nixnet Servers Down

### ISSUE THREAD

**Issue by vindicatorr** [privacytools/privacytools.io#2157]
## Description
"uncensored.any.dns.nixnet.xyz" and "uncensored.ny1.dns.nixnet.xyz" do not work.
"uncensored.lv1.dns.nixnet.xyz" does work.

## Why I am making the suggestion
Simply pointing out the service does not appear to be maintained.
Anycast worked at one point. I moved to ny1, then that also stopped working. Now I'm on the final lv1.

## My connection with the software
User

I believe @Amolith maintains those servers (https://github.com/privacytools/privacytools.io/issues/1206 & https://docs.nixnet.services/User:Amolith). (I don't know if any of that will poke that person).

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Amolith** [comment]
> I believe @Amolith maintains those servers (#1206 & https://docs.nixnet.services/User:Amolith). (I don't know if any of that will poke that person).

Yes, I do maintain the DNS resolvers. I am aware of the reliability issues and have been working on a proper, long-term fix rather than simply slapping a band-aid on them for now.

Part of the issue that I *won't* be able to fix is that those servers are fairly lightweight yet receive a *lot* of traffic. I don't currently have the funds to upgrade them and keep them upgraded in the long run nor do I receive enough donations to cover the cost.

**Comment by vindicatorr** [comment]
And now lv1 is also down. I'm out.

**Comment by Amolith** [comment]
I'm sorry you're frustrated but the servers update, upgrade, and, when required, reboot autonomously to ensure timely security fixes. Never once have I guaranteed 100% uptime. If you'll check back, you'll notice that all three of them work perfectly fine.

* https://uncensored.ny1.dns.nixnet.xyz/dns-query?name=whoami.v4.powerdns.org&type=A
* https://uncensored.lv1.dns.nixnet.xyz/dns-query?name=whoami.v4.powerdns.org&type=A
* https://uncensored.lux1.dns.nixnet.xyz/dns-query?name=whoami.v4.powerdns.org&type=A

**Comment by Amolith** [comment]
Note that I'm not trying to convince you to use my resolvers. Frankly, it would make maintaining them a little easier if fewer people did. I'm simply explaining their behaviour.

**Comment by wylel** [comment]
@Amolith would this be something you would want pulled from the site because of this?

On another note, we might want to add a section for uptime guarantees, as if there arent enough columns on that page. Not really sure the best way to portray this if its a common occurrence for any provider listed.

To be clear, not bashing NixNet, just throwing out options and ideas.

**Comment by Amolith** [comment]
> @wylel: would this be something you would want pulled from the site because of this?

I think that would be a good idea, yes; there's no sense in recommending a service that barely works. When I'm eventually able to upgrade the resolvers and reliably support more users, we can talk about potentially "re-listing" them! :slightly_smiling_face:

**Comment by Amolith** [comment]
@wylel I just noticed that they're still listed on the site; any ETA for removal? My resolvers are technically still running but I do discourage people from using them and it would be best if they were removed from PrivacyTools.

**Comment by Amolith** [comment]
These servers will be shut down on September 10th.
