### ISSUE TITLE
❌ Software Removal |  Canary Mail

### ISSUE THREAD

**Issue by romanholiday12** [privacytools/privacytools.io#2170]
## Description
I suggest removing Canary Mail.

## Why I am making the suggestion
It is not open source.

In the first place, iOS is not open source.
Like Windows, it should not be recommended.

## My connection with the software
none

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by bcye** [comment]
Maybe rather move it to worth mentioning? It might interesting for users who like a clean design

**Comment by romanholiday12** [comment]
> Maybe rather move it to worth mentioning? It might be interesting for users who like a clean design

PTIO is a place to introduce software with good privacy protection, not software with good design.

For example, Cryptomator's UI is terrible.

**Comment by bcye** [comment]
Ok, fair. Though, just that it's closed source isn't a reason to remove it. There are multiple closed source apps/services on PTIO and it wasn't a reason to deter it from being added.

**Comment by LongJohn-Silver** [comment]
The PT team has already stated multiple times that they even though libre software is always the best solution, they are not completely against proprietary software if it proves to accomplish its function. This is the case with Canary. iOS doesn't have a better solution therefore it is recommended, if you know a libre project that could work better than this one suggest it and it will probably be listed, otherwise I doubt they will remove it.

**Comment by romanholiday12** [comment]
> The PT team has already stated multiple times that even though libre software is always the best solution, they are not completely against proprietary software if it proves to accomplish its function. This is the case with Canary. iOS doesn't have a better solution therefore it is recommended, if you know a libre project that could work better than this one suggest it and it will probably be listed, otherwise I doubt they will remove it.

Why are you forcing yourself to recommend an email client for iOS?
In the first place, iOS itself should be deprecated.

**Comment by LongJohn-Silver** [comment]
I am not part of the team, I am just explaining you the situation. And anyways I think it is the correct thing to do, following your traing of thought we should not recommend anything that can't be installed on GrapheneOS since Android isn't much of a better place than iOS when it comes to privacy. It all comes to threat model, if you think that not letting companies see your e-mails is where you stop here you have the tools. 
Not everyone is going to use Qubes.

**Comment by dngray** [comment]
> iOS doesn't have a better solution therefore it is recommended, if you know a libre project that could work better than this one suggest it and it will probably be listed, otherwise I doubt they will remove it.

Pretty much this, and if you're using iOS you're not using open source anyway.

**Comment by romanholiday12** [comment]
It is inconsistent to recommend iOS when you claim that Windows should not be used.

**Comment by bcye** [comment]
Where exactly is iOS recommended?

**Comment by dngray** [comment]
Its more of a case of a person having an iPhone and going "what can i run on this thing", its not like they are going to ditch their phone, so its a case of best-case. It's also not like they can "use Linux on it".

That also being said, the reason Windows was not recommended was in regard to the Cortana analytics and stuff that was included with Windows. You do have to go to some extent to reduce the telemetry that is sent back to Microsoft.

Apple has never done this, to the same extent, while they've had some usage telemetry, they've not being trying to set up a as competitor to google's advertising empire. In addition to that, they were one of the first, with Safari to block third party tracking cookies by default, even before Firefox.
