### ISSUE TITLE
🆕 Software Suggestion | LibreWolf

### ISSUE THREAD

**Issue by spikecodes** [privacytools/privacytools.io#2184]
## Basic Information

**Name:** LibreWolf
**Category:** Browsers → Browser Recommendations For Desktop 
**URL:** https://librewolf-community.gitlab.io/docs/
**Source Code:** https://gitlab.com/librewolf-community/browser

## Description
This project is an independent fork of Firefox, with the primary goals of privacy security and user freedom. It is the community run successor to [LibreFox](https://github.com/intika/Librefox).

LibreWolf uses more than 500 privacy/security/performance settings, patches, LibreWolf-Addons (optional) and is designed to minimize data collection and telemetry as much as possible (updater, crashreporter and Firefox's integrated addons that don't respect privacy are removed).

## Why I am making the suggestion

LibreWolf is a great alternative to Firefox for people who want great privacy and security without Mozilla bloating up their browser.

## My connection with the software

I have no connection to the software.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
I know there isn't another issue regarding LibreWolf but I'm sure it has already been discussed in the forum the reasons of why it wouldn't be listed. First and foremost it doesn't have an Android build which will make recommendations harder, it also doesn't have a Windows build which would make it unsuitable as of now (but I know they are working on it). 

Then there's the fact that I feel all the "bloat" they remove are features or options which can be easily disabled in the settings or in about:config, and if you think about Firefox being used by regular Janes and Joes it makes sense for them to be there, I'm sure my mother doesn't care about that safe browsing connecting to Google's list of safe websites, and I prefer that since at least there's a layer of protection. Firefox couldn't create something designed *only* for the most private conscious individuals, it would go to ruin, which takes me to another point.

I think it would be the best scenario if Privacy Tools would lead as many people as possible towards using Firefox, I really like forks like this or Waterfox, or whatever other crazy stuff there is, but if Mozilla dies all that dies, too, there's no way any kind of group of individuals or whatever that will keep that alive, and even if it's possible it will just make things harder. You need a lot of time and money to do something like this, and we should help them.

Lastly, there's the fact of whether or not they are able to maintain LibreWolf up to date. I'm not saying they don't do it, just that it is important that they do it, not for a couple of months, but for a long period of time, constantly.

**Comment by spikecodes** [comment]
I see what you mean about Windows builds marked as "coming soon".

> Janes and Joes it makes sense for them to be there, I'm sure my mother doesn't care about that safe browsing connecting to Google's list of safe websites

Well, this site is for privacy tools. I doubt the average Jane, Joe or Mom would even use Firefox for privacy in the first place. If LibreWolf supported Windows, it would be a good addition. I'm closing this issue but if they add Windows support, I'll reopen it.

**Comment by LongJohn-Silver** [comment]
> I see what you mean about Windows builds marked as "coming soon".
> 
> > Janes and Joes it makes sense for them to be there, I'm sure my mother doesn't care about that safe browsing connecting to Google's list of safe websites
> 
> Well, this site is for privacy tools. I doubt the average Jane, Joe or Mom would even use Firefox for privacy in the first place. If LibreWolf supported Windows, it would be a good addition. I'm closing this issue but if they add Windows support, I'll reopen it.

Well, Privacy Tools is not designed for power users only, the list tools and you decided where it's enough. Still, this is my opinion, I don't take any decisions, just giving my two cents, maybe the admins decide to list it.

**Comment by spikecodes** [comment]
I don't think they can list it until it has Windows support.

**Comment by notDevagya** [comment]
experimental windows support is available, don't know if they added that recently

**Comment by spikecodes** [comment]
Thanks! I'm reopening this issue now that Windows builds are available.

**Comment by freddy-m** [comment]
Just to clarify: we closed this issue because it is notoriously difficult to maintain a browser without a dedicated team. The maintainers will give up, updates will stop and the browser will die. Hence, we don't recommend LibreWolf, or any other, similar, Firefox fork.

**Comment by Thorin-Oakenpants** [comment]
and it's configuration is a complete mess
- outdated prefs since day one
- conflicting prefs
- prefs that reduce security
- overkill on prefs and redundancy (making it harder to revert)
- locking prefs (unnecessary)
- failure to even keep up with prefs changes (and yet they still claim it uses the "ghacks" user.js)
- no clear strategy of what they are doing and way too many wishwashy conflicts
   - which takes precedence: security or privacy?
   - what about compat

This harks back to initika's compilation in the old librefox: where he basically scraped together every single pref he could find under the sun, merged them all into a single file, and set them all to break everything possible

The whole thing **_seems_** to be, and at least attracts all the crazies, about how to beat the jewgle femto mozilla botnet into submission and be based.

Now, if they sorted all that pref out, and valued security over privacy, and it was a one-click install and forget (e.g. with uBO and some easy toggles for compat), you know, like Tor Browser with HTTPS+NoScript and a slider, then maybe: but then WTF is so hard about dropping a user.js in and installing uBO.

I may sound harsh, and I have zero love for Librewolf, but it's a solution looking for a problem: they all are.

**Comment by Thorin-Oakenpants** [comment]
https://librewolf-community.gitlab.io/docs/
![utterBS](https://user-images.githubusercontent.com/16656956/115527466-9a1c6d80-a280-11eb-8a97-9562bfdb3006.png)

Utter BS. PK's is ~40% deprecated items and basically hasn't been touched in 3+ years. Arkenfox's updates have been practically ignored
- https://gitlab.com/librewolf-community/settings/-/issues/21
-  ^^ that's it: last time they looked was FF75
- to be fair, there have probably been a few other changes, but it certainly isn't from arkenfox, and it certainly isn't with any coherent plan (or schedule) in mind

/rant : pisses me off that they proudly mention arkenfox (or rather ghacks) as some sort of approval stamp - it's not.

---

In fact, @shreyasminocha - please remove any reference to arkenfox (ghacks) from your documentation: you're not using the user.js as is, so I do not care about any license

**Comment by fxbrit** [comment]
Hi @Thorin-Oakenpants , osx maintainer of librewolf here, but I will mainly speak for myself in this comment.
I want to start this by saying that I value your opinion and I respect you and your work a lot: I've used arkenfox's user.js for a long time and I've learnt a lot from your documentation, so of course it would be stupid to come out here and say that I don't care about your thoughts on the current status of librewolf, or even worst that I don't know about your effort towards privacy. I have no problem admitting that I share some of arkenfox's views and I apply them to my own personal setup: in the end me, as many others, would not be able to achieve improvements in privacy without a strong collaborative effort with the privacy community.

For this very reason I think that all the technical stuff that you mentioned in your comments should not go unheard by the librewolf community, but in fact it should be taken into consideration as something that we should work on, as a chance for improvement.
Yes, you sounded harsh, but your criticism is something that we should build on, and your opinion on the need of a hardened Firefox alternative is respectable, although I do not agree with this as I don't see an issue with having more than a single option when it comes to privacy tools. I think that user empowerement is a good thing and more privacy related projects means a growing privacy community that can learn by working togheter, despite having different views on software, and even on the value of a project.
To me, for example, librewolf is a valuable alternative that allows me to improve my privacy, and I honestly highly appreciate that it is a community effort that tries to be private by default, versus a Mozilla software that can be configured to be more private. Generally speaking, I dislike this idea that we should only have one single major option, I want to move my life away from centralization of any kind, I see enough of it in everyday's life.

The only thing that personally bothered me, is the part where you mention that _'The whole thing seems to be, and at least attracts all the crazies, about how to beat the jewgle femto mozilla botnet into submission and be based'_. I don't know if I might have poorly interpreted your words, but if you mean that librewolf engages in conspiracy, homophobic, misogynist, alt-right or any kind of hateful stuff, I want to take a stance against this by saying that I never saw any of our project members spread this kind of bullshit, as otherwise I would have never joined the project in the first place given that I do not associate myself with hate speech of any kind.
I don't enjoy this kind of talk, and nobody I interacted with in the project ever acted in a way that was hateful. For this reason it makes me sad and a bit bothered to see a project I contribute to being associated to this kind of stuff, if anything I found our gitter and reddit community to be positive places to hang in.
Additionally, I feel like when it comes to this kind of stuff, everyone is always put under this american umbrella, which, as a european citizen, is something I dislike. Again, maybe I misunderstood your words, but I don't care and I don't even bother being informed about 'alt-right based pro trump or whoever' crap, so I don't like seeing me (and others) being put under the umbrella like this. I've seen enough linux and privacy community members turn political and hateful recently, I would like to keep our browser out of this crap: it should be a community not a political clan, and I think it is, so using this as a way to talk down on the project under privacytools.io suggestion is a bit offending, at least to me.
Peace 🐟

**Comment by Thorin-Oakenpants** [comment]
> I think it is, so using this as a way to talk down on the project under privacytools.io suggestion is a bit offending, at least to me

Except the "attract crazies" part, it is **_all relevant_** as to why librewolf should not be added to PTIO. PS: I edited my earlier post to clarify that the "crazies" was not meant to imply the librewolf devs

But I agree this is not the right forum. I've said my piece. If you want to continue the discussion, and you seem level headed, then I'm happy to invite you to a private repo - just let me know @fxbrit

**Comment by fxbrit** [comment]
> Except the "attract crazies" part, it is all relevant as to why librewolf should not be added to PTIO. PS: I edited my earlier post to clarify that the "crazies" was not meant to imply the librewolf devs

I understand your stance, the part you quoted wasn't meant to undermine your criticism of librewolf, I just thought that the part about being based and stuff was a bit out of place and I do not recognize our community in that phrase. Btw, thank you for editing that part, I appreciate your honesty. Other than the devs I think that every LW community I interacted with so far has been hate-free, I hope it stays that way for the longest.

I honestly don't have anything else to add at the moment, but if you want to further discuss about technical and non-technical stuff, or if you just want to add something to what we said so far, feel free to ping me at any given time in a private repo of your liking. Thank you @Thorin-Oakenpants :-)

Oh, btw, sorry PTIO folks about cluttering your thread with this discussion lol.

**Comment by freddy-m** [comment]
> Oh, btw, sorry PTIO folks about cluttering your thread with this discussion lol.

Thats fine, though I think a private reop would be a better option for this discussion 👍🏼

**Comment by Thorin-Oakenpants** [comment]
FYI: partially resolved: https://gitlab.com/librewolf-community/docs/-/commit/ad68c29b2dcec9a537a6d8cbd1bb86ab8e24051b

**Comment by Thorin-Oakenpants** [comment]
FYI: [note: this does not mean I am endorsing anything]
- https://gitlab.com/fxbrit/settings/-/blob/master/README.md
- @fxbrit has been busy [work in progress]
   - removed approx 350 prefs so far (only 200 to go IMO) [I do not know how LW will handle reverting these for existing profiles]
   - unlocked prefs
   - some better pref choices
   - I assume it lands in the next release, IDK

**Comment by fxbrit** [comment]
thank you for updating this post, appreciate your fairness. your wake up call wasn't unheard on our side :-)

regarding the releases, I do not have a precise timeline but we are going to review the changes and then it's likely going to be in a release,. the old configuration will be marked as legacy and it will be considered deprecated.

**Comment by ph00lt0** [comment]
@freddy-m librewolf remains actively updated, I see a lot of advantages when comparing the default Firefox browser. I think this should be reconsidered.

**Comment by Thorin-Oakenpants** [comment]
No. I see a lot of advantages in a user.js with Firefox compared with a default Librewolf. 

Librewolf is still too much of a mess. Not sure where the pref changes are at, but it was at 400 which is about 150 too many, and I'm allowing some URL prefs in that number for defense-in-depth. And now it's actively developing a settings UI which includes undermining RFP 🤦

**Comment by fxbrit** [comment]
> advantages in a user.js with Firefox compared with a default Librewolf

why it gotta be one or the other? not saying this to have librewolf included on PTIO, it's fair from them to stay minimal and not include every project. but just in general, why we gotta necessarily go at war.

> Librewolf is still too much of a mess. Not sure where the pref changes are at, but it was at 400 which is about 150 too many, and I'm allowing some URL prefs in that number for defense-in-depth

actually I believe we are at 350 counting the URLs you mentioned.

> And now it's actively developing a settings UI which includes undermining RFP 🤦

some contributors are working on a UI that exposes the settings so that we don't actually require users to go out their way to change stuff. one of them is going to be a setting that allows to have dark mode even with RFP, but it will be disabled by default and probably even locked (we changed the way we lock stuff, it will be only for weird stuff like that), with a big warning saying what it might do. we noticed that many users where either using an extensions or disabling rfp completely just for the dark theme, so we tried something else.

I always appreciate your frankness and fairness and I even thanked you for that as you had been nothing but nice ever since our conversation started, but this feels a bit like whispering the accomplishments and screaming the failures - I assume you consider the above mentioned pref as failure given that you called it 'undermining RFP', and I'm not trying to argue with this opinion of yours on the specific setting in this thread -, meh.

**Comment by ph00lt0** [comment]
> No. I see a lot of advantages in a user.js with Firefox compared with a default Librewolf.

The reason I prefer Librewolf is because it comes with the right settings out of the box. Additionally it has removed all connections like pocket to Mozilla fully. An average user will likely not install a custom user profile, but using another browser is a lot easier.

**Comment by Thorin-Oakenpants** [comment]
> why it gotta be one or the other? ... why we gotta necessarily go at war.

On a PTIO thread about adding it to PTIO .. it's not about one or the other, it's about whether or not it fits PTIO, and clearly nothing has changed enough yet (IMO), and some ["blockers"](https://github.com/privacytools/privacytools.io/issues/2184#issuecomment-822308725) can't change. Glad it is down to 350, keep at it.

I mentioned a couple of things to back up my **_copypasta reply_** of ph00lt0's comment (I'm taking the piss), to show that "opinions" need facts.

re: the "undermining" of RFP is not an "opinion", it's a mathematical proven certainty, and criticism is a valid answer. This RFP dark/light option is incredibly dangerous (in FPing), and you know some of my background in this FPing - and knowing that, not a single mention of it to me at you know where. It doesn't matter the default or warnings (lock might help a bit), if you allow the option users will take it (and unlocking it wouldn't be much of a barrier?) - users (you have to take a lowest common denominator) are not simply not informed enough (they're not meant to be) - it's meant to be a lock-in for a reason. To me this comes back to LW's core purpose - see my earlier comment "no clear strategy of what they are doing and way too many wishwashy conflicts" - so you want to use RFP but then allow users to alter it. Where is the leadership on this? - these are questions for LW itself, not for this thread, as you say, `-meh`

No-one is at "war". Calm down and chive on, as they say :)

@ph00lt0 

The reason I prefer a user.js is because it comes with the right settings out of the box. Additionally it has removed all connections like pocket to Mozilla. An average user will likely not install a fork, and just dropping a small file into a profile is a lot easier

Stop posting *opinions*. How do you know it's the right settings? Show me why pocket is a privacy/tracking concern - it does nothing unless you sign up. How is dropping a user.js (without reading it) into a profile any less confusing than just installing a new browser (with no detailed info on the 350+ changes)? How does a fully documented user.js *confuse* people - information overload aside, it's purpose is the exact opposite of what you're claiming? .. etc

**Comment by fxbrit** [comment]
> On a PTIO thread about adding it to PTIO .. it's not about one or the other, it's about whether or not it fits PTIO, and clearly nothing has changed enough yet (IMO), and some "blockers" can't change. Glad it is down to 350, keep at it.

yeah that was probably me overreacting. it's valid reasoning and I wish more people were actually concerned with how open source projects are doing or at least reviewing the code to a capacity. fair.

> criticism is a valid answer

for sure, but I'm also sure you can see why we are considering something like this. I can sum it up with: unlocking that pref is harder than changing the RFP one probably. this is better for a private discussion than having it here tho, unless someone is specifically interested.

**Comment by youdontneedtoknow22** [comment]
> unless someone is specifically interested.

I'm interested in this discussion tbh. So if you want to discuss it somewhere else, it would be nice if it's open for others to see.

**Comment by fxbrit** [comment]
FYI: pants kinda moved the discussion to [this issue](https://github.com/arkenfox/user.js/issues/1218) where she dropped some knowledge, it's very much worth a read.
