### ISSUE TITLE
Reopen Vivaldi Browser Issues

### ISSUE THREAD

**Issue by KosmoEskudo** [privacytools/privacytools.io#2209]
Please reopen https://github.com/privacytools/privacytools.io/issues/2206 (more recent) or https://github.com/privacytools/privacytools.io/pull/717 , since no one has said a *why* not to include it. I have researched Vivaldi, and have written up my findings in [this article](https://write.privacytools.io/kolivro/vivaldi-and-privacy) and I don't see a *why* not to include it.

The only thing that has been said is that it is closed source, and this issue is explained by Vivaldi [here](https://vivaldi.com/blog/vivaldi-browser-open-source/).

Translated with www.DeepL.com/Translator

**Comment by 0ndrey** [comment]
Ridiculous excuses. Even if there is 0.00001% closed source code, it is still impossible to recommend this browser.

**Comment by Evernow** [comment]
> The only thing that has been said is that it is closed source, and this issue is explained by Vivaldi here.

All yes, which basically sums down to "We use open source code in our closed source browser, so it's ok"

By that logic iOS should be recommended [since it uses open source parts in its closed source OS](https://developer.apple.com/opensource/).

Give me a break, come back when we can have fully reproducable builds of it, like we do for [firefox](https://tests.reproducible-builds.org/debian/bullseye/amd64/index_reproducible.html)
