### ISSUE TITLE
❌ Software Removal | AnonAddy

### ISSUE THREAD

**Issue by goc980** [privacytools/privacytools.io#2280]
## Description
I suggest the removal of AnonAddy.

## Why I am making the suggestion
AnonAddy is an unknown operator. There is no mention of it in the privacy policy or in the terms of use.
Transparency of the operator is important for an email service.

## My connection with the software
No connection

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
> AnonAddy is an unknown operator. There is no mention of it in the privacy policy or in the terms of use.

It's not run by an unknown operator, you just didn't look hard enough.

- https://anonaddy.com/privacy/
- https://anonaddy.com/contact/
- https://anonaddy.com/faq/#whos-behind-anonaddy

**Comment by goc980** [comment]
> > AnonAddy is an unknown operator. There is no mention of it in the privacy policy or in the terms of use.
> 
> It's not run by an unknown operator, you just didn't look hard enough.
> 
>     * https://anonaddy.com/privacy/
> 
>     * https://anonaddy.com/contact/
> 
>     * https://anonaddy.com/faq/#whos-behind-anonaddy

There is no address listed there.

**Comment by dngray** [comment]
> There is no address listed there.

That generally only happens when it's a company's address.

In this case he likely doesn't have a "office space" so the only address he could list is where his house is. That obviously has privacy implications for William and is not a requirement or practice any company does.

Alternatively you could choose to self host: https://anonaddy.com/self-hosting/
