### ISSUE TITLE
❌ Software Removal | ProtonVPN

### ISSUE THREAD

**Issue by Baker-ux-dot** [privacytools/privacytools.io#2306]
## Description
I suggest you remove ProtonVPN. They are doing misleading marketing.

## Why I am making the suggestion
[Their website](https://protonvpn.com/) says "All apps are open source and audited". 
But that's a lie.
[Currently the latest Linux clients](https://protonvpn.com/download-linux) are closed source.

## My connection with the software
I'm irrelevant.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment]
The GUI for the Linux client was previously a community maintained one, recently the team started to work on their own (which I think it is forked from the previous but with some improvements). They are probably waiting for it to be a bit more stable and with a tidier code writing before releasing the source code, since similar procedures have been taken in the past.

Regarding the killswitch, as I mentioned it wasn't official, so there's that.

**Comment by demostanis** [comment]
What do you mean? It's right there. https://github.com/ProtonVPN/linux-cli

**Comment by Dyrimon** [comment]
> What do you mean? It's right there. https://github.com/ProtonVPN/linux-cli

TBH, it's been just released. So I can't blame the OP for suspecting. But it *is* released finally. 

I think it's time to close the issue.
