### ISSUE TITLE
❌ Software Removal | ProtonMail 

### ISSUE THREAD

**Issue by rusty-snake** [privacytools/privacytools.io#2318]
## Description

ProtonMail started to use Google Recaptcha on (better: after) login, see https://github.com/ProtonMail/WebClient/issues/242.

## My connection with the software

user

- [ ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by waltercool** [comment]
There is no technical reason to do that. Unless you can prove Google Recaptcha used on Protonmail is a threat to your information

**Comment by rusty-snake** [comment]
Well, it forces me to connect to Google, download javascript code from them and execute it.

**Comment by waltercool** [comment]
@rusty-snake And what's the issue about that? Do you see a leak of information or identifier going to Google?

I put the main requests/responses obtained from reCaptcha, there is no cookie data or e-tag related to identify you as an user.

Seems like protonmail makes a proxy for Google requests, just like Brave and Ungoogled Chromium does.

**Comment by waltercool** [comment]
I did an early analysis about this 13 days ago at https://mastodon.social/@protonmail/106255978912201582, but I did a bad analysis. The cookie IS created, but it's empty

**Comment by rusty-snake** [comment]
>  Do you see a leak of information or identifier going to Google?

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN

> Natural persons may be associated with online **identifiers** provided by their devices, applications, tools and protocols, **such as internet protocol addresses**, cookie identifiers or other identifiers such as radio frequency identification tags. This may leave traces which, in particular when combined with unique identifiers and other information received by the servers, may be used to create profiles of the natural persons and identify them.

so yes

**Comment by waltercool** [comment]
@rusty-snake ReCaptcha request is initiated by ProtonMail, you only use Google to download assets and confirm ReCaptcha.

For example, under your strict anti-google point of view because Google may track you by IP address, PrivacyTools suggest Firefox as browser, then you go to Firefox.com, they use a Google request on their website.

![Screenshot_20210601_025529](https://user-images.githubusercontent.com/86944/120279802-e2b64600-c284-11eb-974b-eeaf14af614a.png)

Firefox uses Google Safe Browsing also https://wiki.mozilla.org/Security/Safe_Browsing 

Should PrivacyTools remove Firefox?

**Comment by rusty-snake** [comment]
Ideally yes, but Firefox is special in that it has no alternatives. ProtonMail has alternatives (Disroot and Tutanota to name the free ones).
