### ISSUE TITLE
🆕 Software Suggestion | Snips

### ISSUE THREAD

**Issue by maelp** [privacytools/privacytools.io#970]
## Basic Information

**Name:** Snips
**Category:** Software / Voice assistants
**URL:** https://snips.ai

## Description

Snips is the first true private-by-design Voice AI assistant, because it works 100% offline. It is available in english, french, german, japanese, spanish, italian, and more coming! You can build your own assistants in a few minutes by using the web console and download the offline assistants to your Raspberry Pi, Linux, osX, Android, or iOS. It is also 100% free for makers!

**Comment by blacklight447-ptio** [comment]
I think this would require a new category on the website, maybe stuff like "digital assistants?

**Comment by maelp** [comment]
Would be great!

**Comment by FreddyMarsden** [comment]
Mycroft could also be an addition potentially?

**Comment by koenvervloesem** [comment]
Snips has been bought by Sonos and the Snips Console needed to create Snips apps is not available anymore since January 31, 2020.

Last time I checked, Mycroft still sends your voice commands to their own servers. See their [privacy policy](https://mycroft.ai/embed-privacy-policy/):

> When you use our Services, your audio commands are transmitted to Mycroft for processing, as part of the Services. We may also collect other metadata about your audio commands, such as the time and location.

An alternative voice assistant is [Rhasspy](https://rhasspy.github.io/rhasspy-voltron/) (disclaimer: I'm a contributor). As far as I know, this is the only voice assistant that:

- works 100% offline (no voice commands are sent to a server on the internet)
- is entirely free/open source with a permissive license
- works well with freely available home automation software

Many Snips users (including me) have moved on to Rhasspy.

**Comment by blacklight447-ptio** [comment]
So @koenvervloesem , am i right thinking that Snips is now no longer fully open source?

**Comment by koenvervloesem** [comment]
It never was fully open source. Only specific parts such as the NLU component.

**Comment by blacklight447-ptio** [comment]
interesting, and how is the situation for Rhasspy?

**Comment by koenvervloesem** [comment]
The code is fully open source, MIT licensed. It's a toolkit, so you can interface it with various voice related projects, both online and offline or open source and proprietary. See https://github.com/rhasspy.

**Comment by freddy-m** [comment]
If this is not open source then I don't think we need to add it, given that we don't even have a section dedicated to voice assistants.

@privacytools/editorial

**Comment by LongJohn-Silver** [comment]
[Almond](https://almond.stanford.edu/) is another libre software voice assistant, just in case. 

Maybe this is relevant for accessibility, though, so it may be worthwhile to have it listed, even though it's a bit out of boundaries from the project goal.
